DROP SCHEMA IF EXISTS dateStudents;
CREATE SCHEMA dateStudents;
USE dateStudents;

CREATE TABLE students(
	RA VARCHAR(15) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(50),    
    CPF VARCHAR(11),
    CONSTRAINT PRIMARY KEY(RA)
);
