DROP SCHEMA IF EXISTS dataStudents;
CREATE SCHEMA dataStudents;
USE dataStudents;

CREATE TABLE students(
	RA VARCHAR(6) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,    
    CPF VARCHAR(11) NOT NULL UNIQUE,
    CONSTRAINT PRIMARY KEY(RA)
);
